feat: add ability to customize API root path in service URL
nextcloud/integration_openai pull request #143
Opened 2024-10-11 21:10 UTC by edward-ly

Resolves #105.

2024-10-14 22:56 UTC, kyteinsky commented on src/components/AdminSettings.vue
> +						:title="t('integration_openai', 'Leave empty to use {openaiApiUrl}', { openaiApiUrl: 'https://api.openai.com/v1' })">
let's add v1 to line 15 too

2024-10-14 23:01 UTC, kyteinsky commented on src/components/AdminSettings.vue
>  						{{ t('integration_openai', 'This can be a local address with a port like {example}. In this case make sure \'allow_local_remote_servers\' is set to true in config.php', { example : 'http://loca
same here, v1 should be appended to the url

2024-10-14 23:04 UTC, kyteinsky commented
Adding a preview like a computed URL for an example endpoint like chat completions `http://localhost:8080/v1/chat/completions` when the service url field is modified would be convenient as Julien said here: https://github.com/nextcloud/integration_openai/issues/105#issuecomment-2396639019

2024-10-15 09:57 UTC, julien-nc requested changes
I agree with the review from @kyteinsky . Appart from that, all good.
For appconfig values, using IAppConfig in the migration step was the right thing to do :+1:

2024-10-16 05:59 UTC, edward-ly commented
Done. I decided to use another NcNoteCard to display the preview as I thought NcTextField's helperText in dark mode was too faint to be usable, but I am open to other ideas.

2024-10-16 06:18 UTC, kyteinsky approved these changes

2024-10-16 10:48 UTC, julien-nc approved these changes
:+1:

2024-10-16 10:48 UTC, merged