Update README with more config info
nextcloud/integration_openai pull request #46
Opened 2023-09-24 14:52 UTC by jospoortvliet

Was asked about configuring various AI things. That you have to set up things in Connected Accounts wasn't really obvious.

2023-09-25 08:43 UTC, julien-nc requested changes
:blue_heart: A few minor change suggestions. WDYT?

2023-09-25 08:43 UTC, julien-nc commented on README.md
> +Users can choose to disable the Nextcloud Assistant.
```suggestion
Users can choose to disable the Nextcloud Assistant even if the Assistant app is installed.
```

2023-09-25 08:43 UTC, julien-nc commented on README.md
> +There is a "Connected accounts" **admin** settings section to set your OpenAI API key. This is also where you can connect to a Local AI instance.
```suggestion
There is a "Connected accounts" **admin** settings section to set your OpenAI API key. This is also where you can set a LocalAI instance URL if you prefer using LocalAI.
```

2023-09-28 13:18 UTC, provokateurin commented on README.md
> +![configure AI options](https://github.com/nextcloud/integration_openai/assets/551757/a6a78fa6-3598-4e17-90b2-0f7548df3ab6)
These screenshots should be added to the repo itself rather than using this asset thingy.

2025-05-20 15:35 UTC, julien-nc approved these changes
:+1:

2025-05-20 15:35 UTC, merged